# Site settings
title: 'Ruslan writes code'
email: mrrusof@gmail.com
description: "Uebung macht den Meister."
baseurl: ""
url: "http://ruslanledesma.com"
github_username: mrrusof
linkedin_username: rusl%C3%A1n-ledesma-garza-78a65277

# Build settings
markdown: kramdown
